---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.geo_app.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-matrix
          image: {{ .Values.matrix.image }}
          command: ["cmatrix"]  
          ports:
            - containerPort: {{ .Values.matrix.port }}
        - name: {{ .Chart.Name }}
          image: {{ .Values.geo_app.image }}:{{ .Values.geo_app.tag }}
          env:
            - name: TOKEN
              valueFrom:
                secretKeyRef:
                  name: token
                  key: token
            - name: USER_STRING
              value: {{ .Values.env.USER_STRING }}  
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.geo_app.port }}