---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ .Chart.Name }}
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: {{ .Values.image.port }}
      targetPort: {{ .Values.image.port }}
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}

